export type DailyQuote = { text: string; by: string }

export const QUOTES: DailyQuote[] = [
  { text: 'There is nothing impossible to him who will try.', by: 'Alexander the Great' },
  { text: 'I am not afraid of an army of lions led by a sheep. I am afraid of an army of sheep led by a lion.', by: 'Alexander the Great' },
  { text: 'Heaven cannot brook two suns, nor earth two masters.', by: 'Alexander the Great' },
  { text: 'If you are afraid, don’t do it. If you are doing it, don’t be afraid.', by: 'Genghis Khan' },
  { text: 'Conquering the world on horseback is easy. It is dismounting and governing that is hard.', by: 'Genghis Khan' },
  { text: 'Impossible is a word to be found only in the dictionary of fools.', by: 'Napoleon Bonaparte' },
  { text: 'A leader is a dealer in hope.', by: 'Napoleon Bonaparte' },
  { text: 'Glory is fleeting, but obscurity is forever.', by: 'Napoleon Bonaparte' },
  { text: 'If you want a thing done well, do it yourself.', by: 'Napoleon Bonaparte' },
  { text: 'I will either find a way or make one.', by: 'Hannibal Barca' },
  { text: 'I will not ask my men to do what I will not do.', by: 'Hannibal Barca' },
  { text: 'When I am in the battlefield, I love it more than my wedding night.', by: 'Khalid ibn al-Walid' },
  { text: 'Do you see a handspan on my body that is not scarred? This is how a soldier should look.', by: 'Khalid ibn al-Walid' },
  { text: 'It is better to be a lion for a day than a sheep all your life.', by: 'Timur' },
  { text: 'Trust in God, but tie your camel.', by: 'Timur' },
  { text: 'Move like lightning and strike before the enemy knows he is at war.', by: 'Subutai' },
  { text: 'The army that arrives first with the most, wins.', by: 'Subutai' },
  { text: 'The king who is not a warrior is a king in name only.', by: 'Chandragupta Maurya' },
  { text: 'An enemy should be won over by gifts, or crushed without mercy.', by: 'Chandragupta Maurya' },
  { text: 'There, where I have passed, the grass will never grow again.', by: 'Attila the Hun' },
  { text: 'I shall never rest until I have reached the sea.', by: 'Attila the Hun' },
  { text: 'He who defends everything defends nothing.', by: 'Frederick the Great' },
  { text: 'The greatest and noblest pleasure is to discover new truths, and the next is to shake off old prejudices.', by: 'Frederick the Great' },
  { text: 'Artillery adds dignity to what would otherwise be a vulgar brawl.', by: 'Frederick the Great' },
  { text: 'Don’t be afraid to give up the good to go for the great.', by: 'John D. Rockefeller' },
  { text: 'I do not think there is any other quality so essential to success as perseverance.', by: 'John D. Rockefeller' },
  { text: 'The secret of success is to do the common thing uncommonly well.', by: 'John D. Rockefeller' },
  { text: 'The man who dies rich dies disgraced.', by: 'Andrew Carnegie' },
  { text: 'Put all your eggs in one basket, and then watch that basket.', by: 'Andrew Carnegie' },
  { text: 'As I grow older, I pay less attention to what men say. I just watch what they do.', by: 'Andrew Carnegie' },
  { text: 'If I had learned education I would not have had time to learn anything else.', by: 'Cornelius Vanderbilt' },
  { text: 'I have always served the public because, like every other man, it is to my interest to do so.', by: 'Cornelius Vanderbilt' },
  { text: 'Go as far as you can see; when you get there you’ll be able to see farther.', by: 'J.P. Morgan' },
  { text: 'A man always has two reasons for doing anything: a good reason and the real reason.', by: 'J.P. Morgan' },
  { text: 'Whether you think you can, or you think you can’t — you’re right.', by: 'Henry Ford' },
  { text: 'Failure is simply the opportunity to begin again, this time more intelligently.', by: 'Henry Ford' },
  { text: 'Coming together is a beginning; keeping together is progress; working together is success.', by: 'Henry Ford' },
  { text: 'If you want to know the value of money, go and try to borrow some.', by: 'John Jacob Astor' },
  { text: 'The man who makes a habit of his life to go to bed at nine will do a great work.', by: 'John Jacob Astor' },
  { text: 'Permit me to issue and control the money of a nation, and I care not who makes its laws.', by: 'Mayer Amschel Rothschild' },
  { text: 'Buy when there’s blood in the streets, even if the blood is your own.', by: 'Mayer Amschel Rothschild' },
  { text: 'I am rich by God’s grace, without extortion, and ready to lose all for the sake of God and my honor.', by: 'Jakob Fugger' },
  { text: 'A deal is a deal, and the man who keeps it will keep his fortune.', by: 'Jakob Fugger' },
  { text: 'There is only one boss. The customer. And he can fire everybody in the company.', by: 'Sam Walton' },
  { text: 'Swim upstream. Go the other way. Ignore the conventional wisdom.', by: 'Sam Walton' },
  { text: 'High expectations are the key to everything.', by: 'Sam Walton' },
  { text: 'Stay hungry. Stay foolish.', by: 'Steve Jobs' },
  { text: 'Your time is limited, so don’t waste it living someone else’s life.', by: 'Steve Jobs' },
  { text: 'Innovation distinguishes between a leader and a follower.', by: 'Steve Jobs' },
  { text: 'The people who are crazy enough to think they can change the world are the ones who do.', by: 'Steve Jobs' },
  { text: 'When something is important enough, you do it even if the odds are not in your favor.', by: 'Elon Musk' },
  { text: 'Persistence is very important. You should not give up unless you are forced to give up.', by: 'Elon Musk' },
  { text: 'I think it is possible for ordinary people to choose to be extraordinary.', by: 'Elon Musk' },
  { text: 'I came, I saw, I conquered.', by: 'Julius Caesar' },
  { text: 'The die is cast.', by: 'Julius Caesar' },
  { text: 'Experience is the teacher of all things.', by: 'Julius Caesar' },
  { text: 'It is easier to find men who will volunteer to die than to find those who will endure pain with patience.', by: 'Julius Caesar' },
  { text: 'I found Rome a city of bricks and left it a city of marble.', by: 'Augustus' },
  { text: 'Make haste slowly.', by: 'Augustus' },
  { text: 'I have united all under Heaven. Let the standard be one.', by: 'Qin Shi Huang' },
  { text: 'A wall is only as strong as the will of the men who stand behind it.', by: 'Qin Shi Huang' },
  { text: 'Right action is better than knowledge; but to do what is right, we must know what is right.', by: 'Charlemagne' },
  { text: 'Let my armies be the rocks and the trees and the birds in the sky.', by: 'Charlemagne' },
  { text: 'You cannot be a leader and ask other people to follow you unless you know how to follow too.', by: 'Cyrus the Great' },
  { text: 'Diversity in counsel, unity in command.', by: 'Cyrus the Great' },
  { text: 'In this sign, conquer.', by: 'Constantine the Great' },
  { text: 'By this victory, the Empire is remade.', by: 'Constantine the Great' },
  { text: 'The people think of wealth and power as the greatest fate, but in this world a spell of health is the best state.', by: 'Suleiman the Magnificent' },
  { text: 'To command is to serve, nothing more and nothing less.', by: 'Suleiman the Magnificent' },
  { text: 'I have conquered an empire, but I have not been able to conquer myself.', by: 'Peter the Great' },
  { text: 'I am a pupil and I need to be taught.', by: 'Peter the Great' },
  { text: 'A monarch should be ever intent on conquest, lest his neighbors rise in arms against him.', by: 'Akbar the Great' },
  { text: 'Peace is the greatest of victories.', by: 'Akbar the Great' },
  { text: 'Life is like unto a long journey with a heavy burden. Let thy step be slow and steady, that thou stumble not.', by: 'Tokugawa Ieyasu' },
  { text: 'The strong manly ones in life are those who understand the meaning of the word patience.', by: 'Tokugawa Ieyasu' },
  { text: 'If you win, win generously.', by: 'Tokugawa Ieyasu' },
  { text: 'Politics is the art of the possible.', by: 'Otto von Bismarck' },
  { text: 'The great questions of the day will not be settled by speeches, but by iron and blood.', by: 'Otto von Bismarck' },
  { text: 'Fools learn from experience. I prefer to learn from the experience of others.', by: 'Otto von Bismarck' },
  { text: 'Truth is like the sun. You can shut it out for a time, but it ain’t goin’ away.', by: 'Elvis Presley' },
  { text: 'When things go wrong, don’t go with them.', by: 'Elvis Presley' },
  { text: 'Ambition is a dream with a V8 engine.', by: 'Elvis Presley' },
  { text: 'It’s amazing how much you can do if you just keep moving.', by: 'Chuck Berry' },
  { text: 'Roll on. The music is supposed to make you feel good.', by: 'Chuck Berry' },
  { text: 'Knowledge speaks, but wisdom listens.', by: 'Jimi Hendrix' },
  { text: 'I’m the one that’s got to die when it’s time for me to die, so let me live my life the way I want to.', by: 'Jimi Hendrix' },
  { text: 'You can’t always get what you want. But if you try sometimes, you just might find you get what you need.', by: 'Mick Jagger' },
  { text: 'Lose your dreams and you will lose your mind.', by: 'Mick Jagger' },
  { text: 'Life is what happens to you while you’re busy making other plans.', by: 'John Lennon' },
  { text: 'A dream you dream alone is only a dream. A dream you dream together is reality.', by: 'John Lennon' },
  { text: 'Count your age by friends, not years. Count your life by smiles, not tears.', by: 'John Lennon' },
  { text: 'I won’t be a rock star. I will be a legend.', by: 'Freddie Mercury' },
  { text: 'The most important thing is to live a life you can be proud of.', by: 'Freddie Mercury' },
  { text: 'I always knew I was a star. And now the rest of the world seems to agree with me.', by: 'Freddie Mercury' },
  { text: 'A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.', by: 'Bob Dylan' },
  { text: 'He not busy being born is busy dying.', by: 'Bob Dylan' },
  { text: 'The times they are a-changin’.', by: 'Bob Dylan' },
  { text: 'Every guitar player has something unique. Identify what makes you different and develop it.', by: 'Jimmy Page' },
  { text: 'Let the music do the talking.', by: 'Jimmy Page' },
  { text: 'I don’t know where I’m going from here, but I promise it won’t be boring.', by: 'David Bowie' },
  { text: 'Aging is an extraordinary process where you become the person you always should have been.', by: 'David Bowie' },
  { text: 'Turn and face the strange.', by: 'David Bowie' },
  { text: 'Wanting to be someone else is a waste of the person you are.', by: 'Kurt Cobain' },
  { text: 'I’d rather be hated for who I am than loved for who I am not.', by: 'Kurt Cobain' },
  { text: 'The duty of youth is to challenge corruption.', by: 'Kurt Cobain' },
]

export function quoteForDate(iso: string): DailyQuote {
  const [y, m, d] = iso.split('-').map(Number)
  const day = Math.floor(Date.UTC(y ?? 2026, (m ?? 1) - 1, d ?? 1) / 86_400_000)
  const i = ((day % QUOTES.length) + QUOTES.length) % QUOTES.length
  return QUOTES[i] ?? QUOTES[0]!
}
